### ISSUE TITLE
Usb "Device Mode"

### ISSUE THREAD

**Issue by gabrielgagz** [gabrielgagz/android_device_razer_pearlyn#6]
The Usb "Device Mode" layer implemented by Razer is controlled by this pseudo-driver?:

https://github.com/gabrielgagz/android_kernel_razer_pearlyn/blob/cm-14.1/drivers/misc/rzr/usbdevice.c

Doing a echo on /proc/usb_device, a "0", puts the device in debug mode and an "1" puts the device in "host mode". Right now the only way to switch this mode is doing an echo via adb or manually. There isn't a implementation in settings for this, because it's a vendor adition.

The 'Usb Debugging' option in LOS does nothing...

As far i know we have this options:

1) Adding an extra  option in settings (Example: https://github.com/LineageOS/android_device_motorola_athene/tree/cm-14.1/cmactions)
2) Forking the TvSettings package and make a custom package?
3) Forking the TvSettings package and make a custom package, and replace 'Usb Debugging' with 'Device Mode'
4) A daemon who capture the change of the adb_secure? system property and triggers 'echo 0 >/proc/usb_device'
5) Find out why "Usb Debugging" is not working properly and get a proper fix in ...kernel?

The selinux context for all this is already done.

PS: Also there is a system property (persist.sys.rzr.device_mode) associated in this: https://github.com/gabrielgagz/android_device_razer_pearlyn/blob/cm-14.1/rootdir/etc/init.razer.peripherals.sh

**Comment by lbdroid** [comment]
I would call this a "would be nice", but not a critically important feature. Frankly, I think that most people would find ADB-over-IP to be a lot more useful for a device like this, which really needs to have a permanent connection to a local network anyway.

1) Something along this line would seem optimal.
2) I'd hesitate to fork anything where the upstream code is likely to *EVER* be changed. That adds unnecessary maintenance burden.
3) No, that would have serious and negative consequences. See note below.
4) No, that would have serious and negative consequences. See note below.
5) I kind of suspect that you may not quite understand this setting. See note below.

NOTE: things that say "USB debugging" are somewhat mislabelled. It doesn't really mean usb debugging, it means Android Debug Bridge. For instance, disabling USB debugging will disable ADB-over-IP. So you definitely don't want to take that out or alter its function. From what you've said (elsewhere), it is my understanding that ADB-over-IP is working perfectly well, and when you switch the USB mode (echo 0 > /proc/usb_device), that ADB-USB also works. That tells me that the "USB Debugging" setting (which really means "ADB Enabled") is actually working correctly and should not be altered. You also shouldn't have anything watching the value of system property adb_secure, since adb_secure has connotations that also apply to ADB-over-IP.

Its too bad that they didn't have the sense to put a more proper USB connector on the device. The Type-A socket is really intended for devices that are EXCLUSIVELY USB hosts. This device really should have a Type-C socket, or in the very least, an extended (3.0) micro-B, both of which include an ID pin for determining if the USB should be in host or peripheral mode that the kernel can use in order to automatically switch between modes.

**Comment by gabrielgagz** [comment]
Well, so first of all we can re-label "USB debugging" with an overlay .
And 1) seems to be the more accurate solution. A new sub-option under the new "Android Debug Bridge" category.
  
This is a LOW PRIORITY "issue", but it's a feature of the device and should be supported.

**Comment by lbdroid** [comment]
I think that if anybody decided to rename it, it really should be GOOGLE. Right now, everybody who uses ADB understands the meaning of the control, even if it is named unclearly.

**Comment by gabrielgagz** [comment]
In a phone. I'm assigning this to myself, i have to start to do something....

**Comment by gabrielgagz** [comment]
Done with this commit: https://github.com/gabrielgagz/android_device_razer_pearlyn/commit/34ae1bdd5d63ff879ac61ba71100987889e16746
